# -A List all entries except for . and ..
# -F Display a slash (`/') immediately after each pathname that is a directory,
#    an asterisk (`*') after each that is executable, an at sign (`@') after
#    each symbolic link, an equals sign (`=') after each socket, a percent sign
#    (`%') after each whiteout, and a vertical bar (`|') after each that is a
#    FIFO.
# -h Use human-readable units
# -l List in long format
alias ll='ls -lhAF'
alias ls='ls -F'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Useful to pretty-print outputs from JSON APIs.
# Usage: `curl "https://example.com/api/" | json`
# See https://docs.python.org/2.7/library/json.html
alias json='python -m json.tool'
